import { useState, useRef } from 'react'
import { Box, Button, Stack, Typography } from '@mui/material'
import Head from 'next/head'
import TextField from '@mui/material/TextField';
import { useEffect } from 'react';
import { supabase } from '@/pages/api/supabase'
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select from '@mui/material/Select';
import { useRouter } from 'next/router';
import axios from 'axios'
import Image from 'next/image'
import { competition } from '@/pages/api/competition';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { DatePicker } from '@mui/x-date-pickers/DatePicker';
import { TimePicker } from '@mui/x-date-pickers/TimePicker';
import * as React from 'react';
import dayjs from 'dayjs';
const market = [
  {
    "type": "one",
    "homehelper": "1 - 0",
    "helper": "1 - 1",
    "awayhelper": "0 - 1",
    "homelabel": "%",
    "drawlabel": "%",
    "awaylabel": "%",
    "home": "onenil",
    "draw": "oneone",
    "away": "nilone",
    "twoway": "visible"
  },
  {
    "type": "two",
    "homehelper": "2 - 1",
    "helper": "2 - 2",
    "awayhelper": "1 - 2",
    "homelabel": "%",
    "drawlabel": "%",
    "awaylabel": "%",
    "home": "twoone",
    "draw": "twotwo",
    "away": "onetwo",
    "twoway": "visible"
  },
  {
    "type": "two zero",
    "homehelper": "2 - 0",
    "helper": "",
    "awayhelper": "0 - 2",
    "homelabel": "%",
    "drawlabel": "",
    "awaylabel": "%",
    "home": "twonil",
    "draw": "",
    "away": "niltwo",
    "twoway": "hidden"
  },
  {
    "type": "three one",
    "homehelper": "3 - 1",
    "helper": "",
    "awayhelper": "1 - 3",
    "homelabel": "%",
    "drawlabel": "",
    "awaylabel": "%",
    "home": "threeone",
    "draw": "",
    "away": "onethree",
    "twoway": "hidden"
  },
  {
    "type": "threenil",
    "homehelper": "3 - 0",
    "helper": "",
    "awayhelper": "0 - 3",
    "homelabel": "%",
    "drawlabel": "",
    "awaylabel": "%",
    "home": "threenil",
    "draw": "",
    "away": "nilthree",
    "twoway": "hidden"
  },
  {
    "type": "threes",
    "homehelper": "3 - 2",
    "helper": "3 - 3",
    "awayhelper": "2 - 3",
    "homelabel": "%",
    "drawlabel": "%",
    "awaylabel": "%",
    "home": "threetwo",
    "draw": "threethree",
    "away": "twothree",
    "twoway": "visible"
  },
  {
    "type": "others",
    "homehelper": "4 - 4",
    "helper": "other scores",
    "awayhelper": "0 - 0",
    "homelabel": "%",
    "drawlabel": "%",
    "awaylabel": "%",
    "home": "fourfour",
    "draw": "otherscores",
    "away": "nilnil",
    "twoway": "visible"
  },
]
export default function AddB() {
  //all hooks
  //end of match hooks
  const [value, setValue] = React.useState(dayjs('2022-04-07'));
  // curl -XGET 'https://api.football-data.org/v4/matches/330299' -H "X-Auth-Token: 24753eb3f6354d84a1f6ab4326215755"
  useEffect(() => {


  }, [])
  //rOPyD8FDYr6EBMkVajheTQtUdh1wptS6ESbAUFscRo9gK5I8U7CNAhgOd6VZ
  const rand = Math.random().toString().slice(2, 8);
  const router = useRouter()
  const form = useRef();
  function submitForm(event) {
    // Prevent the form from submitting.
    event.preventDefault();
    // Set url for submission and collect data.
    const formData = new FormData(event.target);
    // Build the data object.
    const data = {};
    formData.forEach((value, key) => (data[key] = value));
    // Log the data.
    const matching = { "match_id": rand }
    const datas = {
      ...data,
      ...matching
    }
    console.log(datas)
    const upbet = async () => {
      const { error } = await supabase
        .from('bets')
        .insert(datas)
      console.log(error)
      if (error === null) {
        alert("bet uploaded")
        router.push("/admin/bets")
      }
    }
    upbet();
  }
  return (
    <Stack direction="column" justifyContent="center" alignItems="center"
      sx={{ width: "100%", height: "100%", padding: "16px", background: "whitesmoke" }}>
      <Head>
        <title>Add Bets-AFC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head><form onSubmit={submitForm} ref={form}>
        <Box>
          <Typography variant='h4' sx={{ fontFamily: 'Poor Story, cursive' }}>Add New BETs and Markets</Typography>
          <FormControl fullWidth sx={{ margin: "8px" }}>
            <InputLabel id="demo-simple-select-label">League Name</InputLabel>
            <Select
              labelId="demo-simple-select-label"
              id="demo-simple-select"
              name="league"
              label="Select League Name or Title"
            >

              <MenuItem value="others">Others ,Please Specify Below</MenuItem>
              {
                competition.competitions.map((c) => {
                  return (
                    <MenuItem value={c.name} key={c.area.name + c.name}>{c.area.name} {c.name} ({c.code})</MenuItem>
                  )
                })
              }
            </Select>
          </FormControl>
          <TextField
            label="specify others"
            helperText="Please type the name of the league if not seen in the Options Above"
            variant='standard'
            name='otherl'
          />
          <Stack direction="row" spacing={3} sx={{ marginTop: "12px" }}>
            <TextField
              id="standard-helperText"
              label="Home Team"
              helperText="Name of Home Team is Required"
              variant="outlined"
              defaultValue=''
              name='home'
            />
            <TextField
              id="standard-helperText"
              label="Away Team"
              helperText="Name of Away Team is Required"
              variant="outlined"
              defaultValue=''
              name='away'
            /></Stack>
          <Stack sx={{ marginTop: "12px" }} direction="row" spacing={4}>
            <LocalizationProvider dateAdapter={AdapterDayjs}>
            <DatePicker
              label="Date"
              value={value}
              onChange={(newValue) => {
                setValue(newValue);
                console.log(newValue)
              }}
              renderInput={(params) => <TextField {...params} helperText='the format is mm/dd/yyyy' name='date'/>}
            />
            <TimePicker
              label="Time"
              value={value}
              onChange={(newValue) => {
                setValue(newValue);
                console.log(newValue) 
              }}
              renderInput={(params) => <TextField {...params} 
              name='time'/>}
            />
          </LocalizationProvider></Stack>

        </Box>
        <Typography sx={{ marginTop: "8px" }}>Input Your Desired Percentage for each Market</Typography>
        <Stack direction="column" spacing={3} sx={{ padding: "8px" }}> {
          market.map((data) => {

            return (
              <Stack direction='column' spacing={2} key={data.type}>
                <Typography variant='caption'>{data.type}</Typography>
                <Stack direction='row' className='homeAwayDraw' spacing={3}>
                  <TextField label={data.homelabel} variant='standard' helperText={data.homehelper} name={data.home} 
              type='float'/>
                  <TextField label={data.drawlabel} style={{ visibility: `${data.twoway}` }} type='float' variant='standard' helperText={data.helper} name={data.draw} />
                  <TextField label={data.awaylabel} variant='standard' type='float' helperText={data.awayhelper} name={data.away} />
                </Stack>
              </Stack>
            )
          })}</Stack>
        <Button type='submit' variant="contained">
          Create Bet
        </Button>
      </form>
    </Stack>
  )
}
