import Cover from './cover'
import Head from 'next/head';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import { Box } from '@mui/system';
import PropTypes from 'prop-types';
import {useState,useContext, useEffect} from 'react'
import { Typography,Stack } from '@mui/material';
import Deposit from '../deposit';
import Withdrawal from '../withdrawal';
import {AppContext} from '../api/Context'
import { useRouter } from 'next/router';
function TabPanel(props) {
    const { children, value, index, ...other } = props;
  
    return (
      <div
        role="tabpanel"
        hidden={value !== index}
        id={`simple-tabpanel-${index}`}
        aria-labelledby={`simple-tab-${index}`}
        {...other}
      >
        {value === index && (
          <Box sx={{ p: 3 }}>
            <Typography>{children}</Typography>
          </Box>
        )}
      </div>
    );
  }
  
  TabPanel.propTypes = {
    children: PropTypes.node,
    index: PropTypes.number.isRequired,
    value: PropTypes.number.isRequired,
  };
  
  function a11yProps(index) {
    return {
      id: `simple-tab-${index}`,
      'aria-controls': `simple-tabpanel-${index}`,
    };
  }
export default function Balance(){
    const [value, setValue] = useState(0);
    const {info,setInfo} = useContext(AppContext)
    const handleChange = (event, newValue) => {
      setValue(newValue);
    };
    const router = useRouter()
    useEffect(()=>{
  if(info.logged === false){
      router.push('/login')
    }
    },[])
    return(
        <Cover>
             <Head>
        <title> My Balance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_afc.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
            <Stack justifyContent="center" alignItems="center">
            <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
<Tab label="Withdrawal" {...a11yProps(0)} style={{color:"white"}}/>
    <Tab label="Deposit" {...a11yProps(1)} style={{color:"white"}}/>
  </Tabs>
  <Box>
  <TabPanel value={value} index={0}>
       <Deposit/>
      </TabPanel>
      <TabPanel value={value} index={1}>
   <Withdrawal/>
      </TabPanel>
  </Box>
            </Stack>
        </Cover>
    )
}