import { Box, Stack, Typography,Grid, Button, Divider } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Kick from '../public/adse2.png'
import Kickers from '../public/kick1.jpg'
import  Poster1 from '../public/posters2.jpg'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { getCookies, getCookie, setCookies, removeCookies } from 'cookies-next';
export default function Home() {
  let user = getCookies('logged');

  const router = useRouter()
  if(user.logged === "true"){
    router.push("/user")
  }else{
    console.log("no")
  }
  return (
    <div className={styles.container} style={{background:"#0B1723",maxWidth:"360px",minHeight:"750px",color:"white",opacity:"0.9",padding:"1px",backdropFilter:"blur(8px)"}}>
      <Head>
        <title>ATALANTA FOOTBALL CLUB (AFC)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo_afc.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box >
    <Typography variant="h3" >Home </Typography> 
    <Typography variant='subtitle'>Welcome to ATALANTA FOOTBALL CLUB</Typography></Box>
<Stack sx={{marginTop:"40px"}} direction="column"
  justifyContent="flex-start"
  alignItems="center"
  spacing={2}>
<Grid container sx={{width:"80%"}} justifyContent="center"
  alignItems="center">
  <Grid item xs> <Image src={Kick} alt="winning_big_pic" object-fit="fill" width='260'/></Grid>
      <Grid item xs={8} sx={{minWidth:"320px"}}> 
      <Typography variant="h3" sx={{fontFamily: 'Roboto Condensed, sans-serif',color:"#3F6C98"}}>Why Should You Sign Up ?!</Typography>
      <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}} >  Sign up on our betting site to win big!. Make your first deposit today. We have a wide selection of betting markets and some great promotions to get you started.
   We are the best online betting site in the CryptoCurrency World. We offer a wide range of sports, events and tournaments to bet on, including football, golf and tennis.
    Our dedicated team works hard every day to provide you with an amazing betting experience.</Typography></Grid> 
    <Stack direction="row" spacing={4} sx={{marginTop:"10px"}}>
      <Link href="/login" style={{textDecoration:"none"}}><div>  <Button variant="contained" sx={{fontFamily: 'Secular One, sans-serif'}}>Login</Button></div></Link>
      <Link href="/register/40985" style={{textDecoration:"none"}}><div>
  <Button variant="outlined" sx={{fontFamily: 'Secular One, sans-serif'}}>Register</Button></div></Link>
</Stack>
     </Grid>
     {//backgroundColor:"#F5F9E9"
     }
      <Stack sx={{width:"80%",padding:"10px",marginBottom:"10px"}}  direction="column"
  justifyContent="flex-start"
  alignItems="center"
  spacing={2}>
    <Image src={Kickers} alt="winning_big_pic" object-fit="fill" width='260'/>
      <Typography variant="h3" sx={{fontFamily: 'Roboto Condensed, sans-serif',color:"#3F6C98"}}> Our Amazing Odds and Market</Typography>
        <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}>We have a wide range of betting markets, with odds from our best bookmakers.
         You can find all the latest Premier League fixtures and live scores at AFC football betting page. 
         We have all the latest Premier League fixtures and live scores. We will be posting every teams fixture list for the 2021/22 season, including which games are at home and away. This is a great place to start if you are looking for a quick reference point on when your favourite team plays next or what their upcoming schedule looks like
</Typography>
<Link href="/register/40985" style={{textDecoration:"none"}}>
  <div><Button variant="contained" sx={{fontFamily: 'Secular One, sans-serif'}}>Try Our Odds</Button></div></Link>

      </Stack>
      <Divider sx={{backgroundColor:"white"}}
      />
<Stack sx={{width:"80%",padding:"8px",marginBottom:"10px"}}  direction="column"
  justifyContent="flex-start"
  alignItems="center"
  spacing={2}>
    <Image src={Poster1} alt="winning_big_pic" object-fit="fill" width='300'/>
      <Typography variant="h3" sx={{fontFamily: 'Roboto Condensed, sans-serif',color:"#3F6C98"}}>
      Invitation bonus for each valid 1st level guest</Typography>
      <Stack direction="column">
     <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}>  
      Invite 5 people - get 10 USDT as a bonus      
          </Typography>
          <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}> Refer 10 people - get 24 USDT as a bonus      </Typography>
          <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}>Invite 20 People - Receive 50 SDTs as a bonus   </Typography>
          <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}>Invite 30 people - get 80 SDTs as a bonus   </Typography>
          <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}>Invite 50 people - get 160 SDTs as a bonus   </Typography>
          <Typography sx={{width:"100%",fontFamily: 'Nanum Gothic, sans-serif'}}>Refer 100 people - get 800 USDT as a bonus   </Typography>
      </Stack>
<Link href="/register/40985" style={{textDecoration:"none"}}>
  <div><Button variant="contained" sx={{fontFamily: 'Secular One, sans-serif'}}>
    Sign Up To Start 
    </Button></div></Link>

      </Stack>
      </Stack>
         </div>
  )
}
